### ISSUE TITLE
SideNavigationViewController Crashlytics error

### ISSUE THREAD

**Issue by reeichert** [CosmicMind/MaterialKit#102]
Hi, I'm using Crashlytics in my app, and i get this error while opening my app.

![captura de tela 2015-12-19 as 14 34 26](https://cloud.githubusercontent.com/assets/1337535/11914119/16167d56-a65e-11e5-857e-30f5ef3eb26f.png)

![captura de tela 2015-12-19 as 14 41 11](https://cloud.githubusercontent.com/assets/1337535/11914180/c96e431a-a65f-11e5-9b97-cbca6957ff02.png)
![captura de tela 2015-12-19 as 14 41 25](https://cloud.githubusercontent.com/assets/1337535/11914181/c9714d12-a65f-11e5-843d-f7f083930ed9.png)
something weird is that this error happens only in the version of crashlytics, the same version in the simulator or installed on my phone by xcode, this error does not occur

**Comment by danieldahan** [comment]
Hi, can you send me the initialization code you are using and the version of MK? Thank you!

**Comment by reeichert** [comment]
I have two places that i call sideNavigation 
in appDelegate, case user is already logged
```swift
let storyboard = UIStoryboard(name: "InicioView", bundle: nil)
            
            let mainVC = storyboard.instantiateViewControllerWithIdentifier("MainViewController")
            let sideVC = storyboard.instantiateViewControllerWithIdentifier("LeftMenuViewController")
            
            
            window = UIWindow(frame: UIScreen.mainScreen().bounds)
            window?.rootViewController = SideNavigationViewController(mainViewController: mainVC, sideViewController: sideVC)
            window?.makeKeyAndVisible()
```

and when is new user, after press login button.

```swift
let storyboard = UIStoryboard(name: "InicioView", bundle: nil)                
                    let mainVC = storyboard.instantiateViewControllerWithIdentifier("MainViewController")
                    let sideVC = storyboard.instantiateViewControllerWithIdentifier("LeftMenuViewController")
                    let vc = SideNavigationViewController(mainViewController: mainVC, sideViewController: sideVC)

                    self.presentViewController(vc, animated: true, completion: nil)
```


the version that I use to upload to crashlytics was 1.24.15

**Comment by danieldahan** [comment]
Is the breakage occurring when the user logs in and you switch the controller, or is it happening when they are already logged in? Or both?

**Comment by reeichert** [comment]
on both

**Comment by danieldahan** [comment]
So two things. 

The issue is complaining about BAD_ACCESS, which means that somewhere there is a reference to an object that no longer exists. This could be because of using Storyboards. We do not offer full Storyboard support at this time. 

Further more, rather than using two instances of SideViewController, have you thought of using a single setup that swaps the mainViewController if the user is logged in or becomes logged in? This may help in the memory management of the object. 

I cannot see anything that screams issue in the code. So it is strange that a BAD_ACCESS issue is arising. 

Before I run further testing on this, is it possible to update to the latest version and run these tests?

**Comment by reeichert** [comment]
Yes, I'll update to latest version, like I said, only happens on the version that I install from crashlytics.. on Simulator I don't get this error.

**Comment by danieldahan** [comment]
Yes, I understand. I am updating the closures and animations to use more elaborate ARC support, which would ensure that no cycles occur.

**Comment by LarsDR** [comment]
I just tried installing the latest version, using Carthage (v1.25.8), and I'm getting the same BAD_ACCESS error. I simply added the following to my AppDelegates:
http://s.lars.io/20151221153648_itjuf0wwhi.png

And this is the error:
http://s.lars.io/20151221153611_fw5tb68wps.png

My Storyboard looks like this:
http://s.lars.io/20151221153825_0mtahp1jng.png
(I have some additional views, but I simplified it for this case)

**Comment by danieldahan** [comment]
Hi @LarsDR, Thank you for posting the issue you found. We are looking into this issue and will post a comment later today with the next steps.

**Comment by danieldahan** [comment]
We haven't been able to reproduce this issue. Tomorrow there will be a release with some updates to the memory management of the Side Navigation. If the issue persists, please re-open the ticket or file a new one. Thanks again for bringing this to our attention :)

**Comment by danieldahan** [comment]
@adamdahan Can you try and reproduce this issue. Thank you!

**Comment by banxi1988** [comment]
I Found that Crash when run in Release Mode
 
```
[SideNavigationViewController retain]: message sent to deallocated instance 0x125d371f0
```

**Comment by banxi1988** [comment]
add log

```swift
	/**
	:name:	init
	*/
	public convenience init(mainViewController: UIViewController, sideViewController: UIViewController) {
		self.init()
		self.mainViewController = mainViewController
		self.sideViewController = sideViewController
		prepareView()
		prepareMainViewController()
    NSLog("SideNavigationViewController preSideView")
		prepareSideView()
    NSLog("SideNavigationViewController postSideView")
	}
	
  deinit{
    NSLog("SideNavigationViewController deinit")
  }
```

And the crash output log was

```swift
2015-12-22 15:41:06.734 MyApp[5228:707153] SideNavigationViewController preSideView
2015-12-22 15:41:06.738 MyApp[5228:707153] SideNavigationViewController deinit
2015-12-22 15:41:06.738 MyApp[5228:707153] *** -[SideNavigationViewController retain]: message sent to deallocated instance 
```

**Comment by banxi1988** [comment]
I Found  a workaround by comment two line animation code of `prepareSideView` as below

```swift
//		MaterialAnimation.animationDisabled {
			self.sideView.position.x = -self.sideViewControllerWidth / 2
			self.sideView.zPosition = 1000
//		}
```

**Comment by LarsDR** [comment]
I found that if your mainVC isn't a NavigationControllerViewController, then the side view is deallocated. I got it working (also by commenting out MaterialAnimation.animationDisabled like @banxi1988) now, but only when I'm navigating directly to the NavigationViewController that I have.

**Comment by danieldahan** [comment]
@banxi1988 The workaround that you are doing shouldn't be needed. @adamdahan and I have found a couple things that may be causing the issue. I will let @adamdahan share more about the storyboard usage and how to avoid @LarsDR issue when setting them up. Generally, what is happening with the 

```swift
MaterialAnimation.animationDisabled {
...
}
```

is that the animationDisabled is capturing a lazy loaded property, which is increasing ARCs reference count for that object. What should be happening within the block -- is usage of the sideView with an unowned or weak reference, as well, the lazy property should be converted to an optional and when prepareSideView is called, the sideView may be instantiated thus passing a single reference to the animation block.

I am going to make the changes today and issue a release. Then if you guys can test and try and reproduce the issue, that would be great!

**Comment by adamdahan** [comment]
@LarsDR I tested the side nav and it seems to be working fine as long as the storyboard is configured correctly. 

Because we do not support storyboards the only configuration that will work is following these steps: 

1. Go to your Target's info panel and make sure it is not looking to load the application from a base storyboard. You can see this underneath the "Main Interface" area in the info panel. If it has "Main" there or some other storyboard name - delete it. 

*Side note, I noticed that the image http://s.lars.io/20151221153825_0mtahp1jng.png has a -> Pointing to the root view controller of the storyboard but your code does not use the method instantiateInitialViewController(). You specify which controllers you use so you can remove "Is Initial View Controller" from the identity Inspector.  

If you do step 1. and keep your app delegate the way it is. You should have no problem using the side nav. 

If it does not work, please reference this example project for how to do it: https://github.com/CosmicMind/MaterialKit/tree/master/Examples/Storyboards/SideNavigationViewController

**Comment by LarsDR** [comment]
@adamdahan I actually solved the issue, by moving the 'login' part to a new storyboard, using that as 'initial load', and then transition (with the SideNavigationViewController) to the 'logged in' storyboard, which has a NavigationViewController.

**Comment by adamdahan** [comment]
@LarsDR I do the login / logout pattern you are doing in a lot of apps that are social. The best thing I have found in my experience is to have a view controller that is always at the root of the window. I call this the "BackingViewController".

If the user is logged in then the BackingViewController adds the "Logged in" storyboard's initial view controller as a child via UIViewControllerContainment. 

If the user is logged out the BackingViewController swaps it's child with the "Logged out" storyboard's initial view controller. 

A few reasons why this is a great idea: 

1. It allows for animated transitions without taking snapshots and writing hokus pokus code. 
2. It is safer because the windows.rootViewController is never modified. 
3. Does not cause the "jump" effect when swapped the windows.rootViewController. 

Anyways, 

Glad you got it to work :)

**Comment by banxi1988** [comment]
@danieldahan Hi,I was wandering why we need so many lazy property.
I mean slideView will always be used ,so I can't see any benifit from using lazy property.

**Comment by danieldahan** [comment]
Please try the latest release 1.26.0. There were changes made to the internals of SideNavigationViewController in order to solve the bugs that were described in this issue. As mentioned, we were not able to reproduce the issues specified, so any help in determining if the bug still exists would be much appreciated. Please reopen or create a new ticket if the bug persists. Thank you!

**Comment by banxi1988** [comment]
@danieldahan Hi,I Just try 1.26.0 and It' works very well.
Thank you.

**Comment by danieldahan** [comment]
Awesome! 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
