### ISSUE TITLE
Support Storyboards

### ISSUE THREAD

**Issue by adamdahan** [CosmicMind/MaterialKit#75]

**Comment by WooD1k** [comment]
Hello @adamdahan 
Storyboards support will not be added?

**Comment by adamdahan** [comment]
@wooD1k Yes next release coming next week. We are just tracking our tickets internally now. Sorry I should have informed you. :)

**Comment by danieldahan** [comment]
@WooD1k This is being pushed today with examples :)

**Comment by WooD1k** [comment]
@danieldahan great news, thanks a bunch!

**Comment by danieldahan** [comment]
@WooD1k We added Storyboard examples and programmatic examples. For the SideNavigationViewController, it is not currently possible to use Storyboards on the Controller itself, though, the mainViewController, and sideViewController may use Storyboards. We included an example of how to set this up. We are planning to make some additions to the SideNavigationViewController in general, so this issue will be looked at in more detail. The reason we cannot support it, is because of how the views are currently laid out.

If you need any more assistance, please keep us posted. Thank you!
