### ISSUE TITLE
How to use align function to space a control relative to another on top

### ISSUE THREAD

**Issue by kktam** [CosmicMind/MaterialKit#81]
Hi I have a question on how to the MaterialLayout.align...() function sets.

I am trying to understand how to use these sets of functions to space the control, just like as if I am using the Storyboard.  My understanding is that the easiest way is to use MaterialLayout.alignFromTop() with a fixed size from the top. However, the n-th element, I need to store and calculate the current actual size of each of the n-1 elements on top. Is that a way I can use some functions to maintain and spaces out the elements from each other by m pixels, just like the html css padding?

**Comment by danieldahan** [comment]
Hi @kktam I am preparing an example project with what I believe you are looking for. We can go from there.

**Comment by danieldahan** [comment]
@kktam I have placed an example project for MaterialLayout in the Examples directory. In order to support your request I started working on functions that support  AutoLayout sibling relationships. This will most likely be done today. If you cannot wait, I suggest looking into UIStackView which allows for horizontal and vertical alignment of sibling views, or use AutoLayout through its raw interface. 

The feature you are looking for is very important so it is currently my focus.

**Comment by danieldahan** [comment]
@kktam There is an example project in v1.24.11, which I just released that I believe supports what you are looking for. You are able to align views horizontally and vertically with outer margins, as well as, spacing between the views. In the example, I show how to print out the frame dimensions after they have been laid out. If you have any further questions please reopen or create a new issue. All the best :)

**Comment by kktam** [comment]
Hi Daniel

Can you provide some instructions on how to build and run the sample projects in  v1.24.11? I am getting dyld: Library not loaded: @rpath/MaterialKit.framework/MaterialKit error message.

**Comment by adamdahan** [comment]
@kktam Go to Build Settings and toggle "Embedded Content Contains Swift Code" to YES. Do that on the sample project in question. Should do the trick!

**Comment by kktam** [comment]
That worked! Thank you so much.

**Comment by kktam** [comment]
I have one more interesting observation. It seemed that I need to delete all the reference to MaterialKit.Framework, and relink it in both "Embedded Binaries" as well as "Linked Frameworks and Libraries". Is there a reason why? (Is there a way to automate so that my Github clone will automatically point to the framework build from MaterialKit.xcodeproject?

**Comment by danieldahan** [comment]
Good catch. The issue is the .gitignore file was not catching *.framework files. So references to the build path on my computer were left in. The correct method of installing the framework is to build the MaterialKit on a device or Generic Device schema setting. Then in the project you want to launch, press the Embed Framework button and add the framework. I will make instructions on how to do this shortly. Let me know if you need any other help. 



---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
