### ISSUE TITLE
CardView.divider = false causing cardView to disappear

### ISSUE THREAD

**Issue by sohayb** [CosmicMind/MaterialKit#87]
When I set the cardView divider property to false, the cardView just disappears, I had to set the divider color to clear color to get my desired look.

**Comment by danieldahan** [comment]
I am not able to reproduce the issue. 

1. Is this using Storyboards?
2. Version of test device?
3. May you send some code that shows the construction of the CardView?

**Comment by sohayb** [comment]
1. Yes, I am using the CardView in a StoryBoard,
2. Testing in iPhone 6 simulator, iOS 9.1
3. Where I can send you the sample code?

**Comment by danieldahan** [comment]
If you do not want it to be public, please send to support@cosmicmind.io :)

**Comment by sohayb** [comment]
Preparing the sample now :)

**Comment by danieldahan** [comment]
Hey @sohayb :) 

I reviewed your example code and I believe it is best I answer here so that others may learn from the issue you had pointed out. Within the CardView there is a method called reloadView that is called when a property is altered from its original value, in this case CardView.divider = false. Internal to the reloadView method, AutoLayout is used to create the CardView layout. It looks that the CardView is not actually holding any of its known property values, and a UILabel is added to the CardView to create the effect you are looking for. Since the CardView doesn't have a titleLabel, detailLabel, buttons, or divider, it concludes  using AutoLayout that there is not anything to layout and a height of 0 is applied. 

My suggestion would be to use a MaterialView in this case, which would give you the backgroundColor, shadow, and shape that it looks like you are trying to achieve. If you want a pulse animation, you can use the MaterialPulseView, and if you are looking for a button.target, the RaisedButton looks to be the one you would want in this instance. 

Thoughts?

**Comment by sohayb** [comment]
You're right, I'm not using the CardView where it's supposed to be used, so the error is by design (my case is an odd one, sry for that :) )
Wanted to place a button with an image on it, so I should be better off with the MaterialPulseView.
Closing this for now

**Comment by danieldahan** [comment]
No worries. If you want a button, why not use one of the MaterialButtons? They are fully customizable like the views. They also support an image layer with button.setImage(…)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
