### ISSUE TITLE
NavigationBarView buttons

### ISSUE THREAD

**Issue by paulvanwieren** [CosmicMind/MaterialKit#90]
How do I capture the button presses from NavigationBarView? Even though I've made it IBDesignable, the buttons don't show up in the storyboard.

**Comment by danieldahan** [comment]
@adamdahan Would be able to help with the Storyboards part, as for capturing the press, you can add a target to your button programmatically, like so: 

button.addTarget(self, action: "handleButton:", forControlEvents: .TouchUpInside)

Then you would have a method like this one that gets fired when the button is pressed: 

func handleButton(button: UIButton) {
       // ... do something
}

**Comment by adamdahan** [comment]
Hi @paulvanwieren, 

The buttons won't show up in storyboards because they are not defined as IBOutlet's. IBOutlet is a void type that Interface Builder recognizes. Unfortunately we do not have support for IBOutlet's due to the dynamic nature of .leftButtons / .rightButtons in the NavigationBarView 

The best option for you in this case would be to Subclass the MaterialView and construct a navigation bar look-alike in Storyboards where you can drag standard buttons on the storyboard and drag outlets to your custom subclass. 

Note * If you want the pulse effect on the buttons from the storyboard simply change their class in the identity inspector to one of buttons available in the MaterialKit framework i.e fab, raised or flat. 

We do plan to support storyboards in the future but currently is not part of our road map. Feel free to ping us with some sample code if you get stuck on something. 

All the best

**Comment by paulvanwieren** [comment]
@adamdahan Thanks so much for the explanation. In fact, that's what I've started doing. I'm subclassing things, but in essence I'm just using a material view for the nav bar and dropping material buttons in there.
